meta:
  url:
  title:
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: true
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
      - typescript
      - swift
    plugins: []
    theme: default
  chart: false
  math: false
extends:
  js:
  css: ./style.css
